form_type: "PERSONAL_LOAN_V1"
identification_string: "Personal Loan Application Form"

data_elements:
  fields:
    - name: "Title"
      label: "Title:"
    - name: "Surname"
      label: "Surname:"
    - name: "Forename(s)"
      label: "Forename(s):"
    - name: "Date of Birth"
      label: "Date of Birth:"
    - name: "I.D Card No."
      label: "I.D Card No.:"
    - name: "Passport No."
      label: "Passport No.:"
    - name: "Level of Education (Degree, Diploma,)"
      label: "Level of Education (Degree, Diploma,)"
    - name: "No of Dependants"
      label: "No of Dependants:"
    - name: "Nationality"
      label: "Nationality:"
    - name: "Residential Address"
      label: "Residential Address:"
    - name: "Period of residence (State in years)"
      label: "Period of residence (State in years)"
    - name: "Tel"
      label: "Tel:"
    - name: "Cell"
      label: "Cell:"
      instance: 0
    - name: "e-mail"
      label: "e-mail"
    - name: "Rent/Mortgage Repayment"
      label: "Rent/Mortgage Repayment"
    - name: "Postal Address"
      label: "Postal Address:"
    - name: "Employer's name and address"
      label: "Employer's name and address:"
    - name: "Period in current employment"
      label: "Period in current employment"
    - name: "Occupation"
      label: "Occupation:"
    - name: "Gross monthly income $"
      label: "Gross monthly income $"
    - name: "Net monthly income $"
      label: "Net monthly income $"
    - name: "Loan Amount Required (Specify) $"
      label: "(Specify) $"
      page_num: 1
    - name: "Term preferred"
      label: "Term preferred:"
      page_num: 1
    - name: "Loan Purpose"
      label: "Loan Purpose:"
      page_num: 1

  checkboxes:
    - name: "Mr"
      label: "Mr"
    - name: "Mrs"
      label: "Mrs"
    - name: "Miss"
      label: "Miss"
    - name: "Ms"
      label: "Ms"
    - name: "Married"
      label: "Married:"
    - name: "Single"
      label: "Single:"
    - name: "Male"
      label: "Male:"
    - name: "Female"
      label: "Female:"
    - name: "Owned but Mortgaged"
      label: "Owned but Mortgaged"
    - name: "Owned no mortgage"
      label: "Owned no mortgage"
    - name: "Rented"
      label: "Rented"
    - name: "Other"
      label: "Other"
    - name: "Credit Card"
      label: "Credit Card"
      instance: 0
