form_type: "PERSONAL_LOAN_V1"
identification_string: "Personal Loan Application Form"

data_elements:
  fields:
    - name: "Forename(s)"
      label: "Forename(s):"
      page_num: 0
    - name: "Passport No."
      label: "Passport No.:"
      page_num: 0
    - name: "Level of Education"
      label: "Level of Education (Degree, Diploma,)"
      page_num: 0
    - name: "Nationality"
      label: "Nationality:"
      page_num: 0
    - name: "Present balance"
      label: "Present balance$"
      page_num: 0
    - name: "Account Name & No"
      label: "Account Name & No:"
      page_num: 0

  checkboxes:
    - name: "Mr"
      label: "Mr"
      page_num: 0
    - name: "Married"
      label: "Married"
      page_num: 0
    - name: "Male"
      label: "Male"
      page_num: 0
